"""add audio jobs

Revision ID: 43b5f2b8ebc9
Revises: 7369792e301a
Create Date: 2026-08-10 18:23:30.512348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b5f2b8ebc9'
down_revision: Union[str, Sequence[str], None] = '7369792e301a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('ENHANCE', name='audio_job_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='audio_job_status'), nullable=False),
    sa.Column('input_object_key', sa.String(length=1000), nullable=False),
    sa.Column('output_object_key', sa.String(length=1000), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_jobs_celery_task_id'), 'audio_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_audio_jobs_conversation_id'), 'audio_jobs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_audio_jobs_status'), 'audio_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_audio_jobs_user_id'), 'audio_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_jobs_user_id'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_status'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_conversation_id'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_celery_task_id'), table_name='audio_jobs')
    op.drop_table('audio_jobs')
    # ### end Alembic commands ###
