"""subscription and its token

Revision ID: 7369792e301a
Revises: 5dcf25bc066c
Create Date: 2026-08-04 16:10:03.813461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7369792e301a'
down_revision: Union[str, Sequence[str], None] = '5dcf25bc066c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_durations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_tokens', sa.Integer(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['duration_id'], ['subscription_durations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'duration_id', name='uq_plan_name_duration')
    )
    op.create_table('token_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('available_tokens', sa.BigInteger(), nullable=False),
    sa.Column('lifetime_used_tokens', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('token_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CHAT', 'IMAGE', 'AUDIO', 'PURCHASE', 'REFUND', 'BONUS', name='tokentransactiontype'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('balance_before', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'TRIAL', name='subscriptionstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_song_id'), 'generation_jobs', ['song_id'], unique=False)
    op.drop_constraint(op.f('generation_jobs_song_id_fkey'), 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'generation_jobs', 'songs', ['song_id'], ['id'], ondelete='SET NULL')
    op.add_column('songs', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_songs_conversation_id'), 'songs', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'songs', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_index(op.f('ix_songs_conversation_id'), table_name='songs')
    op.drop_column('songs', 'conversation_id')
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('generation_jobs_song_id_fkey'), 'generation_jobs', 'songs', ['song_id'], ['id'])
    op.drop_index(op.f('ix_generation_jobs_song_id'), table_name='generation_jobs')
    op.drop_table('user_subscriptions')
    op.drop_table('token_transactions')
    op.drop_table('token_wallets')
    op.drop_table('subscription_plans')
    op.drop_table('subscription_durations')
    # ### end Alembic commands ###
