"""add token reservations and transaction idempotency

Revision ID: 97c2660e21a1
Revises: f9088d2aa2d5
Create Date: 2026-08-09 07:26:34.797987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c2660e21a1'
down_revision: Union[str, None] = 'f9088d2aa2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_transactions', sa.Column('request_id', sa.String(length=100), nullable=True))
    op.add_column('token_transactions', sa.Column('reservation_id', sa.UUID(), nullable=True))
    op.drop_index('ix_token_transactions_user_id', table_name='token_transactions')
    op.create_index(op.f('ix_token_transactions_user_id'), 'token_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_transactions_request_id'), 'token_transactions', ['request_id'], unique=False)
    op.create_index(op.f('ix_token_transactions_reservation_id'), 'token_transactions', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_transactions_reservation_id'), table_name='token_transactions')
    op.drop_index(op.f('ix_token_transactions_request_id'), table_name='token_transactions')
    op.drop_index(op.f('ix_token_transactions_user_id'), table_name='token_transactions')
    op.create_index('ix_token_transactions_user_id', 'token_transactions', ['user_id'], unique=True)
    op.drop_column('token_transactions', 'reservation_id')
    op.drop_column('token_transactions', 'request_id')
    # ### end Alembic commands ###
