from prometheus_client import Counter, Histogram
from prometheus_fastapi_instrumentator import Instrumentator


# ============================================================
# HTTP
# ============================================================

instrumentator = Instrumentator(
    should_group_status_codes=False,
    should_ignore_untemplated=True,
    should_respect_env_var=True,
    excluded_handlers=[
        "/metrics",
    ],
)


# ============================================================
# CHAT
# ============================================================

CHAT_REQUESTS_TOTAL = Counter(
    "auralith_chat_requests_total",
    "Total number of chat requests.",
    (
        "service",
    ),
)


CHAT_DURATION_SECONDS = Histogram(
    "auralith_chat_duration_seconds",
    "Chat request duration in seconds.",
    (
        "service",
    ),
)


CHAT_ERRORS_TOTAL = Counter(
    "auralith_chat_errors_total",
    "Total number of chat errors.",
    (
        "service",
        "error_type",
    ),
)


# ============================================================
# LLM
# ============================================================

LLM_REQUESTS_TOTAL = Counter(
    "auralith_llm_requests_total",
    "Total number of LLM requests.",
    (
        "service",
        "model",
        "status",
    ),
)


LLM_DURATION_SECONDS = Histogram(
    "auralith_llm_duration_seconds",
    "LLM request duration in seconds.",
    (
        "service",
        "model",
    ),
)


LLM_ERRORS_TOTAL = Counter(
    "auralith_llm_errors_total",
    "Total number of LLM errors.",
    (
        "service",
        "model",
        "error_type",
    ),
)


LLM_INPUT_TOKENS_TOTAL = Counter(
    "auralith_llm_input_tokens_total",
    "Total number of input tokens processed by the LLM.",
    (
        "service",
        "model",
    ),
)


LLM_OUTPUT_TOKENS_TOTAL = Counter(
    "auralith_llm_output_tokens_total",
    "Total number of output tokens generated by the LLM.",
    (
        "service",
        "model",
    ),
)


# ============================================================
# AUDIO
# ============================================================

AUDIO_JOBS_TOTAL = Counter(
    "auralith_audio_jobs_total",
    "Total number of audio processing jobs.",
    (
        "service",
        "status",
    ),
)


AUDIO_JOB_ERRORS_TOTAL = Counter(
    "auralith_audio_job_errors_total",
    "Total number of audio processing job errors.",
    (
        "service",
        "error_type",
    ),
)


CELERY_TASKS_TOTAL = Counter(
    "auralith_celery_tasks_total",
    "Total number of Celery tasks.",
    ["task", "status"],
)

CELERY_TASK_DURATION_SECONDS = Histogram(
    "auralith_celery_task_duration_seconds",
    "Celery task execution duration in seconds.",
    ["task"],
)

CELERY_TASK_RETRIES_TOTAL = Counter(
    "auralith_celery_task_retries_total",
    "Total number of Celery task retries.",
    ["task"],
)